---
- name: 安装proftpd服务
  sudo: yes
  gather_facts: True
  hosts: "{{ proj_id }}"
  vars:
    proj_install_dir: "{{ proj_dir | default('/usr/local/proftp') }}"
    log_path: /var/log/proftpd.log
    maxclients: 10

  tasks:
    - name: 上传二进制包到远程目录
      unarchive:
        src: files/proftpd-1.3.5.tar.gz
        dest: /usr/src
        owner: root
        group: root
        mode: 0755
        copy: yes

    - name: 在远程主机上解压并安装proftpd
      shell: cd /usr/src/proftpd-1.3.5 && ./configure --prefix={{ proj_install_dir }} && make && make install

    - name: 上传配置文件到远程目录
      template:
        src: files/proftpd.conf.j2
        dest: "{{ proj_install_dir }}/etc/proftpd.conf"
        owner: root
        group: root
        mode: 0755

    - name: 上传启动文件到远程目录
      template:
        src: files/proftp.j2
        dest: /etc/init.d/proftp
        owner: root
        group: root
        mode: 0755
        force: yes

    - name: 添加hosts
      shell: echo {{ ansible_default_ipv4.address }} {{ ansible_nodename }} >>/etc/hosts

    - name: 启动服务
      service:
        name: proftp
        state: started
